[package]
name = "cargo-registry-core"
version = "0.1.0"
authors = ["Greg Wiley <aztec.rex@jammm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
